// Printable receipts. `receiptHtml` is a pure function (easy to verify); `printReceipt`
// opens the receipt in a new window and triggers the browser print/save-as-PDF dialog.

export interface ReceiptLine {
  name: string;
  qty?: number;
  amount: number;
}

export interface ReceiptOptions {
  gymName: string;
  gymAddress?: string | null;
  title: string; // e.g. "Payment receipt"
  reference: string; // invoice number / sale id
  dateLabel: string;
  method: string;
  currency: string;
  lines: ReceiptLine[];
  total: number;
}

function esc(s: string): string {
  return s.replace(
    /[&<>"]/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c] as string,
  );
}

function money(currency: string, n: number): string {
  return `${currency} ${n.toFixed(2)}`;
}

/** Build a self-contained, print-ready receipt HTML document. */
export function receiptHtml(o: ReceiptOptions): string {
  const rows = o.lines
    .map(
      (l) =>
        `<tr><td>${esc(l.name)}${
          l.qty != null ? ` <span class="muted">×${l.qty}</span>` : ''
        }</td><td class="right">${money(o.currency, l.amount)}</td></tr>`,
    )
    .join('');
  return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(o.title)} ${esc(
    o.reference,
  )}</title><style>
*{font-family:ui-sans-serif,system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;box-sizing:border-box}
body{max-width:360px;margin:24px auto;color:#1e293b;padding:0 16px}
h1{font-size:18px;margin:0}
.muted{color:#94a3b8}
.sub{color:#64748b;font-size:12px;margin-top:2px}
.head{text-align:center;border-bottom:1px dashed #cbd5e1;padding-bottom:12px;margin-bottom:12px}
.meta{font-size:12px;color:#475569;display:flex;justify-content:space-between;margin:3px 0}
table{width:100%;border-collapse:collapse;margin:14px 0;font-size:13px}
td{padding:5px 0}
.right{text-align:right}
.total td{border-top:1px solid #cbd5e1;font-weight:700;font-size:15px;padding-top:8px}
.foot{text-align:center;color:#94a3b8;font-size:11px;margin-top:18px}
@media print{body{margin:0}}
</style></head><body>
<div class="head"><h1>${esc(o.gymName)}</h1>${
    o.gymAddress ? `<div class="sub">${esc(o.gymAddress)}</div>` : ''
  }<div class="sub">${esc(o.title)}</div></div>
<div class="meta"><span>Reference</span><span>${esc(o.reference)}</span></div>
<div class="meta"><span>Date</span><span>${esc(o.dateLabel)}</span></div>
<div class="meta"><span>Method</span><span>${esc(o.method)}</span></div>
<table><tbody>${rows}</tbody><tfoot><tr class="total"><td>Total</td><td class="right">${money(
    o.currency,
    o.total,
  )}</td></tr></tfoot></table>
<div class="foot">Thank you! · Generated by GymFlow</div>
</body></html>`;
}

/** Open the receipt in a new window and trigger the print dialog. */
export function printReceipt(o: ReceiptOptions): void {
  const w = window.open('', '_blank', 'width=420,height=640');
  if (!w) return; // popup blocked
  w.document.open();
  w.document.write(receiptHtml(o));
  w.document.close();
  w.focus();
  // Let the new document lay out before invoking print.
  setTimeout(() => {
    try {
      w.print();
    } catch {
      /* user can still print manually */
    }
  }, 250);
}
